displayName=Raid Roulette
author=Artillery
support=https://github.com/BensRepository/Raid-Roulette.git
description=Randomize the next raid you and your friends take on!
tags=
plugins=com.example.ExamplePlugin