displayName=Raid Randomizer
author=ArtilleryRS
support=https://github.com/BensRepository/Raid-Randomizer.git
description=Randomize the next raid you and your friends take on!
tags=
plugins=com.example.ExamplePlugin